import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next App 2',
  description: 'Generated by create next app with lib2',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-4 bg-gray-700 text-white">
          <Link href="/" className="mr-4 hover:underline">Home</Link>
          <Link href="/features" className="hover:underline">Features</Link>
        </nav>
        <main className="p-4">
          {children}
        </main>
      </body>
    </html>
  );
} 